[phases.setup]
nixPkgs = ["postgresql", "postgresql.lib", "python311"]

[phases.install]
cmds = [
  "python3.11 -m venv /opt/venv",
  "/opt/venv/bin/python -m pip install --upgrade pip",
  "/opt/venv/bin/python -m pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmd = "/opt/venv/bin/gunicorn run:app"

[build.env]
LD_LIBRARY_PATH = "/nix/store/*postgresql-*/lib"
PATH = "/opt/venv/bin:$PATH"