[phases.setup]
nixPkgs = ["postgresql", "postgresql.lib"]

[build.env]
LD_LIBRARY_PATH = "/nix/store/*postgresql-*/lib"
PYTHONPATH = "/app/.venv/lib/python3.13/site-packages"

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.start]
cmd = "gunicorn app:app"