[phases.setup]
nixPkgs = ["postgresql", "postgresql.lib", "python311"]

[phases.install]
cmds = [
  "python3.11 -m pip install --upgrade pip",
  "python3.11 -m pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmd = "python3.11 -m gunicorn run:app"

[build.env]
LD_LIBRARY_PATH = "/nix/store/*postgresql-*/lib"